# site settings
author: "Jordan Irwin"
baseurl: 
description: "The thoughts, dreams, rants, lessons, tips, tricks, stories, truths, and lies from one of no particular interest."
highlighter: pygments
name: "JordanIrwin.net"

navigation:
- text: Latest
  url: /
- text: Everything
  url: /archives/
- text: About
  url: /about/

# defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "post"
    values:
      layout: "post"