# site settings
author: "Jordan Irwin"
baseurl: 
description: "Thoughts, rants, tips, tricks, stories, truths, and lies."
highlighter: pygments
name: "JordanIrwin.net"
url: http://www.jordanirwin.net

navigation:
- text: Latest
  url: /
- text: Everything
  url: /archives/
- text: About
  url: /about/
- text: Feed
  url: /feed.xml

# defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "post"
    values:
      layout: "post"