# site settings
author: "Jordan Irwin"
repository: jordansirwin/jordansirwin.github.io.git
# baseurl:
self-css: self.min.css
description: "The thoughts, rants, tips, tricks, stories, truths, and lies of Jordan Irwin"
highlighter: rouge
permalink: pretty
# name: "JordanIrwin.net"
title: "JordanIrwin.net"
url: http://www.jordanirwin.net
useAnalytics: true

plugins:
  - jekyll-redirect-from
  - jekyll-github-metadata

# meta tag for "keywords"
keywords:
  - geek
  - roleplay
  - technology
  - programming
  - video games
  - gaming

# navigation links
navigation:
- text: Latest
  url: /
- text: Everything
  url: /archives/
- text: About
  url: /about/
- text: Feed
  url: /feed.xml
- text: Learning Runner
  url: /learningrunner/privacy/

# default settings
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

exclude:
  - Makefile
  - README.md
  - GemFile
  - GemFile.lock
